import type { Metadata } from 'next'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import InteractiveListingsMapLoader from '@/components/map/InteractiveListingsMapLoader'

export const metadata: Metadata = { title: 'Interactive Map', description: 'Explore approved Vallalar Jeevakarunyam service locations on the Interactive Map.' }
const typeLabels: Record<string, string> = { annadhanam: 'Annadhanam', jeeva_samadhi: 'Jeeva Samadhi', temple: 'Temples & Meditation Centres', stay: 'Affordable Stays', medical: 'Affordable Healthcare', education: 'Affordable Education', community_service: 'Volunteer & Community Service', volunteer: 'Volunteer & Community Service' }
function relationName(value: unknown): string | null { if (!value) return null; if (Array.isArray(value)) { const first=value[0]; return first&&typeof first==='object'&&'name' in first?String(first.name||'')||null:null } return typeof value==='object'&&'name' in value?String((value as {name?:unknown}).name||'')||null:null }
export default async function MapPage() {
 const supabase=await createClient()
 const {data:listings,error}=await supabase.from('listings').select(`id, name, listing_type, google_maps_url, latitude, longitude, village, taluk, states(name), districts(name)`).eq('status','approved').order('name')
 const allListings=listings||[]
 const markerListings=allListings.filter(l=>l.latitude!==null&&l.longitude!==null).map(l=>({id:l.id,name:l.name,listing_type:l.listing_type,latitude:l.latitude as number,longitude:l.longitude as number,google_maps_url:l.google_maps_url,village:l.village,taluk:l.taluk,state_name:relationName(l.states),district_name:relationName(l.districts)}))
 const directoryListings=allListings.filter(l=>l.google_maps_url)
 return <main className="min-h-screen bg-gray-50"><div className="max-w-6xl mx-auto px-4 py-8 md:py-10"><div className="mb-8"><Link href="/" className="inline-flex text-sm font-semibold text-emerald-700 hover:underline mb-5">← Back to Home</Link><p className="text-sm font-semibold text-emerald-700 mb-2">Vallalar Jeevakarunyam</p><h1 className="text-3xl md:text-4xl font-bold text-gray-900">Interactive Map</h1><p className="text-gray-600 mt-3 max-w-3xl leading-7">Explore approved service locations together on one interactive map.</p></div><div className="bg-amber-50 border border-amber-200 rounded-xl p-5 mb-8"><p className="font-semibold text-gray-900">Verification Notice</p><p className="text-sm text-gray-700 mt-1 leading-6">Map listings are published after administrative approval, but may still be awaiting verification by Vallalar Jeevakarunyam. Please confirm location and service details directly before travelling.</p></div>{error&&<div className="bg-red-50 border border-red-200 text-red-700 rounded-xl p-5">Unable to load Interactive Map locations. Please try again later.</div>}{!error&&<InteractiveListingsMapLoader listings={markerListings}/>} {!error&&<section><div className="mb-5"><h2 className="text-2xl font-bold text-gray-900">Location Directory</h2><p className="text-gray-600 mt-1">Approved listings with map information appear here.</p></div>{directoryListings.length===0?<div className="bg-white border border-gray-200 rounded-xl p-8 text-center"><h2 className="text-xl font-semibold text-gray-900">No mapped locations yet</h2></div>:<div className="grid grid-cols-1 md:grid-cols-2 gap-5">{directoryListings.map(l=><article key={l.id} className="bg-white border border-gray-200 rounded-xl p-5 md:p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><span className="inline-flex px-3 py-1 bg-emerald-50 text-emerald-700 text-xs font-semibold rounded-full">{typeLabels[l.listing_type]||l.listing_type}</span><span className="block mt-2 px-3 py-1 bg-amber-50 border border-amber-200 text-amber-800 text-xs font-bold rounded-full w-fit">● Yet to be verified by Vallalar Jeevakarunyam</span><h3 className="text-xl font-bold text-gray-900 mt-3">{l.name}</h3><p className="text-sm text-gray-600 mt-2">{[l.village,l.taluk,relationName(l.districts),relationName(l.states)].filter(Boolean).join(', ')||'Location details available on map'}</p></div><div className="text-3xl">📍</div></div><a href={l.google_maps_url!} target="_blank" rel="noopener noreferrer" className="inline-flex mt-5 px-4 py-2.5 bg-emerald-700 text-white text-sm font-semibold rounded-lg">Open in Google Maps →</a></article>)}</div>}</section>}</div></main>
}
