import Link from 'next/link'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import LogoutButton from '@/components/admin/LogoutButton'

type AdminPageProps={searchParams:Promise<{status?:string;verification?:string}>}
const typeLabels:Record<string,string>={annadhanam:'Annadhanam',jeeva_samadhi:'Jeeva Samadhi',temple:'Temples & Meditation Centres',stay:'Affordable Stays',medical:'Affordable Healthcare',education:'Affordable Education',community_service:'Community Service',volunteer:'Volunteer Services'}
const methodLabels:Record<string,string>={phone:'Phone',field_visit:'Field visit',email:'Email',official_source:'Official source'}
function refresh(){['/admin','/','/annadhanam','/jeeva-samadhi','/temple','/stay','/medical','/education','/volunteer','/map'].forEach(revalidatePath)}

export default async function AdminPage({searchParams}:AdminPageProps){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect('/admin/login')
 const {data:admin}=await supabase.from('admins').select('user_id,role').eq('user_id',user.id).maybeSingle(); if(!admin) return <main className="max-w-6xl mx-auto p-6"><h1 className="text-3xl font-bold">Access Denied</h1></main>
 const p=await searchParams; const statuses=['pending','approved','rejected']; const activeStatus=statuses.includes(p.status||'')?p.status!:'pending'; const dueOnly=p.verification==='due'; const now=new Date()
 async function changeStatus(fd:FormData,status:'approved'|'rejected'){'use server';const id=Number(fd.get('listingId'));if(!Number.isInteger(id))return;const db=await createClient();const {data:{user:a}}=await db.auth.getUser();if(!a)redirect('/admin/login');const {data:aa}=await db.from('admins').select('user_id').eq('user_id',a.id).maybeSingle();if(!aa)return;await db.from('listings').update({status}).eq('id',id).eq('status','pending');refresh()}
 async function approve(fd:FormData){'use server';await changeStatus(fd,'approved')} async function reject(fd:FormData){'use server';await changeStatus(fd,'rejected')}
 async function verify(fd:FormData){'use server';const id=Number(fd.get('listingId')),notes=String(fd.get('verificationNotes')||'').trim(),method=String(fd.get('verificationMethod')||''),months=Number(fd.get('reverifyMonths')||12);if(!Number.isInteger(id)||!notes||!method)return;const db=await createClient();const {data:{user:a}}=await db.auth.getUser();if(!a)redirect('/admin/login');const {data:aa}=await db.from('admins').select('user_id').eq('user_id',a.id).maybeSingle();if(!aa)return;const verified=new Date(),due=new Date(verified);due.setMonth(due.getMonth()+months);const {error}=await db.from('listings').update({verification_status:'verified',verification_notes:notes,verification_method:method,verified_by:a.id,verified_at:verified.toISOString(),next_verification_due_at:due.toISOString()}).eq('id',id).eq('status','approved');if(error){console.error(error);return}refresh()}
 async function unverify(fd:FormData){'use server';const id=Number(fd.get('listingId'));if(!Number.isInteger(id))return;const db=await createClient();const {data:{user:a}}=await db.auth.getUser();if(!a)redirect('/admin/login');const {data:aa}=await db.from('admins').select('user_id').eq('user_id',a.id).maybeSingle();if(!aa)return;await db.from('listings').update({verification_status:'pending_verification',verification_notes:null,verification_method:null,verified_by:null,verified_at:null,next_verification_due_at:null}).eq('id',id).eq('status','approved');refresh()}
 const [pc,ac,rc,dc]=await Promise.all([supabase.from('listings').select('*',{count:'exact',head:true}).eq('status','pending'),supabase.from('listings').select('*',{count:'exact',head:true}).eq('status','approved'),supabase.from('listings').select('*',{count:'exact',head:true}).eq('status','rejected'),supabase.from('listings').select('*',{count:'exact',head:true}).eq('status','approved').eq('verification_status','verified').lte('next_verification_due_at',now.toISOString())]);const counts={pending:pc.count??0,approved:ac.count??0,rejected:rc.count??0,due:dc.count??0}
 let q=supabase.from('listings').select('*,states(name),districts(name)').eq('status',activeStatus).order('created_at',{ascending:false});if(activeStatus==='approved'&&dueOnly)q=q.eq('verification_status','verified').lte('next_verification_due_at',now.toISOString());const {data:listings,error}=await q;if(error)return <main className="p-6">Unable to load listings: {error.message}</main>
 return <main className="max-w-6xl mx-auto p-4 sm:p-6"><div className="flex justify-between gap-4 mb-8"><div><h1 className="text-3xl font-bold">Admin Dashboard</h1><p className="text-gray-600 mt-2">Vallalar Jeevakarunyam Listings</p>{admin.role==='super_admin'&&<Link href="/admin/admins" className="text-emerald-700 font-semibold">Manage Administrators →</Link>}</div><LogoutButton/></div>
 <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-8">{(['pending','approved','rejected'] as const).map(s=><Link key={s} href={`/admin?status=${s}`} className="rounded-xl border p-4 bg-white"><p className="text-sm capitalize">{s}</p><p className="text-3xl font-bold">{counts[s]}</p></Link>)}<Link href="/admin?status=approved&verification=due" className={`rounded-xl border p-4 ${dueOnly?'bg-orange-50 border-orange-400':'bg-white'}`}><p className="text-sm">Re-verification Due</p><p className="text-3xl font-bold text-orange-700">{counts.due}</p></Link></div>
 {!listings?.length?<div className="border rounded-xl p-6">No listings found.</div>:<div className="space-y-5">{listings.map(l=>{const due=l.verification_status==='verified'&&l.next_verification_due_at&&new Date(l.next_verification_due_at)<=now;return <article key={l.id} className="bg-white border rounded-xl p-5 shadow-sm"><div className="flex justify-between gap-3"><div><h3 className="text-xl font-semibold">{l.name}</h3><p className="text-emerald-700 text-sm">{typeLabels[l.listing_type]||l.listing_type}</p><p className="text-sm text-gray-600 mt-1">{l.districts?.name||'-'}, {l.states?.name||'-'}</p></div><span className="text-sm font-semibold capitalize">{activeStatus}</span></div>{l.description&&<p className="mt-4 text-gray-700">{l.description}</p>}
 {activeStatus==='approved'&&<section className={`mt-5 border rounded-xl p-5 ${due?'bg-orange-50 border-orange-300':l.verification_status==='verified'?'bg-emerald-50 border-emerald-200':'bg-amber-50 border-amber-200'}`}><div className="flex flex-wrap justify-between gap-2"><div><h4 className="font-semibold">Vallalar Jeevakarunyam Verification</h4><p className={`text-sm font-semibold mt-1 ${due?'text-orange-700':l.verification_status==='verified'?'text-emerald-700':'text-amber-700'}`}>{due?'⚠ Re-verification due':l.verification_status==='verified'?'✓ Verified by Vallalar Jeevakarunyam':'● Yet to be verified by Vallalar Jeevakarunyam'}</p></div>{l.source_url&&<a href={l.source_url} target="_blank" rel="noopener noreferrer" className="text-emerald-700 text-sm font-semibold">View source ↗</a>}</div>
 {l.verification_status==='verified'?<div className="mt-4 text-sm"><p><strong>Method:</strong> {methodLabels[l.verification_method]||l.verification_method||'-'}</p><p><strong>Note:</strong> {l.verification_notes||'-'}</p>{l.verified_at&&<p><strong>Last verified:</strong> {new Date(l.verified_at).toLocaleDateString('en-IN')}</p>}{l.next_verification_due_at&&<p className={due?'font-bold text-orange-700':''}><strong>Next verification due:</strong> {new Date(l.next_verification_due_at).toLocaleDateString('en-IN')}</p>}<form action={unverify} className="mt-3"><input type="hidden" name="listingId" value={l.id}/><button className="px-4 py-2 border border-amber-600 rounded-lg bg-white">Return to verification queue</button></form></div>:<form action={verify} className="mt-4 space-y-3"><input type="hidden" name="listingId" value={l.id}/><div className="grid sm:grid-cols-2 gap-3"><label className="text-sm font-semibold">Verification method<select name="verificationMethod" required className="block w-full mt-1 border rounded-lg p-2 bg-white"><option value="">Select</option><option value="phone">Phone</option><option value="field_visit">Field visit</option><option value="email">Email</option><option value="official_source">Official source</option></select></label><label className="text-sm font-semibold">Re-verify after<select name="reverifyMonths" defaultValue="12" className="block w-full mt-1 border rounded-lg p-2 bg-white"><option value="3">3 months</option><option value="6">6 months</option><option value="12">12 months</option><option value="24">24 months</option></select></label></div><textarea name="verificationNotes" required rows={3} placeholder="Confirmation note" className="w-full border rounded-lg p-2"/><button className="px-5 py-2.5 bg-emerald-700 text-white font-semibold rounded-lg">✓ Mark as Verified</button></form>}</section>}
 {activeStatus==='pending'&&<div className="mt-5 flex gap-3"><form action={approve}><input type="hidden" name="listingId" value={l.id}/><button className="px-5 py-2 bg-emerald-700 text-white rounded-lg">✓ Approve</button></form><form action={reject}><input type="hidden" name="listingId" value={l.id}/><button className="px-5 py-2 bg-red-600 text-white rounded-lg">✕ Reject</button></form></div>}</article>})}</div>}</main>
}
