create table if not exists public.listing_images (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  image_url text not null,
  storage_path text,
  caption text,
  sort_order integer not null default 0,
  uploaded_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

comment on table public.listing_images is 'Public listing photo gallery. Images may be added or removed by authorized admins even after a listing is approved.';

alter table public.listing_images enable row level security;

grant select on public.listing_images to anon, authenticated;
grant all on public.listing_images to service_role;
grant usage, select on sequence public.listing_images_id_seq to service_role;

drop policy if exists "Public can read approved listing images" on public.listing_images;
create policy "Public can read approved listing images"
on public.listing_images for select
to anon
using (
  exists (
    select 1 from public.listings l
    where l.id = listing_images.listing_id
      and l.status = 'approved'
  )
);

drop policy if exists "Admins can read scoped listing images" on public.listing_images;
create policy "Admins can read scoped listing images"
on public.listing_images for select
to authenticated
using (
  exists (
    select 1 from public.listings l
    where l.id = listing_images.listing_id
  )
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'listing-images',
  'listing-images',
  true,
  5242880,
  array['image/jpeg','image/png','image/webp']::text[]
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;
