create table if not exists public.admin_scopes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.admins(user_id) on delete cascade,
  state_id integer references public.states(id) on delete cascade,
  district_id integer references public.districts(id) on delete cascade,
  listing_type text,
  can_review boolean not null default true,
  can_verify boolean not null default true,
  can_edit boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  constraint admin_scopes_permission_check check (can_review or can_verify or can_edit),
  constraint admin_scopes_district_requires_state check (district_id is null or state_id is not null),
  unique nulls not distinct (user_id, state_id, district_id, listing_type)
);

comment on table public.admin_scopes is
'Defines which state, district and listing category each administrator may manage. NULL geography/category values mean all within that level.';

create index if not exists admin_scopes_user_active_idx
  on public.admin_scopes(user_id, is_active);
create index if not exists admin_scopes_geography_idx
  on public.admin_scopes(state_id, district_id, listing_type)
  where is_active;

alter table public.admin_scopes enable row level security;

drop policy if exists "Admins can read own scopes" on public.admin_scopes;
create policy "Admins can read own scopes"
on public.admin_scopes for select
to authenticated
using (user_id = (select auth.uid()));

create table if not exists public.admin_activity_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  listing_id bigint references public.listings(id) on delete set null,
  action text not null,
  old_status text,
  new_status text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

comment on table public.admin_activity_log is
'Append-only audit trail for administrator listing and scope actions.';

create index if not exists admin_activity_log_actor_idx
  on public.admin_activity_log(actor_user_id, created_at desc);
create index if not exists admin_activity_log_listing_idx
  on public.admin_activity_log(listing_id, created_at desc);

alter table public.admin_activity_log enable row level security;

drop policy if exists "Admins can read own activity" on public.admin_activity_log;
create policy "Admins can read own activity"
on public.admin_activity_log for select
to authenticated
using (actor_user_id = (select auth.uid()));

drop policy if exists "Admins can insert own activity" on public.admin_activity_log;
create policy "Admins can insert own activity"
on public.admin_activity_log for insert
to authenticated
with check (
  actor_user_id = (select auth.uid())
  and exists (
    select 1 from public.admins a
    where a.user_id = (select auth.uid())
  )
);

-- Preserve existing regular-admin behaviour until the super admin narrows it.
insert into public.admin_scopes (
  user_id, state_id, district_id, listing_type,
  can_review, can_verify, can_edit, is_active
)
select a.user_id, null, null, null, true, true, true, true
from public.admins a
where a.role = 'admin'
on conflict do nothing;

drop policy if exists "Admins can read all listings" on public.listings;
create policy "Admins can read scoped listings"
on public.listings for select
to authenticated
using (
  exists (
    select 1 from public.admins a
    where a.user_id = (select auth.uid())
      and a.role = 'super_admin'
  )
  or exists (
    select 1 from public.admin_scopes s
    where s.user_id = (select auth.uid())
      and s.is_active
      and (s.state_id is null or s.state_id = listings.state_id)
      and (s.district_id is null or s.district_id = listings.district_id)
      and (s.listing_type is null or s.listing_type = listings.listing_type)
  )
);

drop policy if exists "Admins can update listings" on public.listings;
create policy "Admins can update scoped listings"
on public.listings for update
to authenticated
using (
  exists (
    select 1 from public.admins a
    where a.user_id = (select auth.uid())
      and a.role = 'super_admin'
  )
  or exists (
    select 1 from public.admin_scopes s
    where s.user_id = (select auth.uid())
      and s.is_active
      and (s.state_id is null or s.state_id = listings.state_id)
      and (s.district_id is null or s.district_id = listings.district_id)
      and (s.listing_type is null or s.listing_type = listings.listing_type)
      and (s.can_review or s.can_verify or s.can_edit)
  )
)
with check (
  exists (
    select 1 from public.admins a
    where a.user_id = (select auth.uid())
      and a.role = 'super_admin'
  )
  or exists (
    select 1 from public.admin_scopes s
    where s.user_id = (select auth.uid())
      and s.is_active
      and (s.state_id is null or s.state_id = listings.state_id)
      and (s.district_id is null or s.district_id = listings.district_id)
      and (s.listing_type is null or s.listing_type = listings.listing_type)
      and (s.can_review or s.can_verify or s.can_edit)
  )
);