create table if not exists public.admin_notification_preferences (
  user_id uuid primary key references public.admins(user_id) on delete cascade,
  notify_pending_listings boolean not null default true,
  email_enabled boolean not null default true,
  notification_email text,
  whatsapp_enabled boolean not null default false,
  whatsapp_number text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_notification_preferences enable row level security;

create policy "Admins can read own notification preferences"
on public.admin_notification_preferences
for select
to authenticated
using (
  user_id = (select auth.uid())
  and exists (select 1 from public.admins a where a.user_id = (select auth.uid()))
);

create policy "Admins can update own notification preferences"
on public.admin_notification_preferences
for update
to authenticated
using (
  user_id = (select auth.uid())
  and exists (select 1 from public.admins a where a.user_id = (select auth.uid()))
)
with check (
  user_id = (select auth.uid())
  and exists (select 1 from public.admins a where a.user_id = (select auth.uid()))
);

insert into public.admin_notification_preferences (user_id)
select a.user_id from public.admins a
on conflict (user_id) do nothing;

create table if not exists public.admin_notification_deliveries (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  admin_user_id uuid not null references public.admins(user_id) on delete cascade,
  channel text not null check (channel in ('email','whatsapp')),
  recipient text,
  status text not null default 'pending' check (status in ('pending','sent','failed','pending_configuration','skipped')),
  provider text,
  provider_message_id text,
  error_message text,
  attempt_count integer not null default 0,
  last_attempt_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (listing_id, admin_user_id, channel)
);

alter table public.admin_notification_deliveries enable row level security;

create index if not exists admin_notification_deliveries_listing_idx on public.admin_notification_deliveries(listing_id);
create index if not exists admin_notification_deliveries_admin_idx on public.admin_notification_deliveries(admin_user_id);
create index if not exists admin_notification_deliveries_status_idx on public.admin_notification_deliveries(status);
