'use client'

import Link from 'next/link'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

export default function ResetPasswordPage(){
 const router=useRouter(); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [done,setDone]=useState(false)
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');if(password.length<8){setError('Password must be at least 8 characters.');return}if(password!==confirm){setError('Passwords do not match.');return}setLoading(true);try{const supabase=createClient();const {error:updateError}=await supabase.auth.updateUser({password});if(updateError){setError(updateError.message);return}setDone(true);await supabase.auth.signOut();setTimeout(()=>router.push('/admin/login'),1500)}catch{setError('Unable to reset password. Please open the newest reset email and try again.')}finally{setLoading(false)}}
 return <main className="min-h-screen bg-gray-50 flex items-center justify-center px-4"><div className="w-full max-w-md bg-white rounded-xl shadow-sm border border-gray-200 p-8"><h1 className="text-3xl font-bold text-gray-900">Create New Password</h1><p className="text-gray-600 mt-2 mb-7">Choose a new password for your admin account.</p>{done&&<div className="mb-5 p-4 bg-emerald-50 border border-emerald-200 rounded-lg text-sm text-emerald-800">Password updated successfully. Returning to Admin Login…</div>}{error&&<div className="mb-5 p-4 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700">{error}</div>}{!done&&<form onSubmit={submit} className="space-y-5"><div><label className="block text-sm font-medium text-gray-700 mb-2">New Password</label><div className="relative"><input type={show?'text':'password'} required value={password} onChange={e=>setPassword(e.target.value)} className="w-full px-4 py-3 pr-20 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-600"/><button type="button" onClick={()=>setShow(v=>!v)} className="absolute inset-y-0 right-0 px-4 text-sm font-semibold text-emerald-700">{show?'Hide':'Show'}</button></div></div><div><label className="block text-sm font-medium text-gray-700 mb-2">Confirm Password</label><input type={show?'text':'password'} required value={confirm} onChange={e=>setConfirm(e.target.value)} className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-600"/></div><button disabled={loading} className="w-full bg-emerald-700 text-white font-semibold py-3 rounded-lg hover:bg-emerald-800 disabled:opacity-50">{loading?'Updating...':'Update Password'}</button></form>}<div className="mt-6 text-center"><Link href="/admin/login" className="text-emerald-700 font-semibold hover:underline">← Admin Login</Link></div></div></main>
}
